services:
  - type: web
    name: wealthwise
    env: static
      buildCommand: NODE_OPTIONS="--max-old-space-size=2048" npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 